# [101 NumPy Exercises for Data Analysis](https://www.machinelearningplus.com/python/101-numpy-exercises-python/)

## L1 Difficulty

In [1]:
# Q. Import numpy as np and print the version number.

import numpy as np

np.__version__

'1.26.4'

In [2]:
# Q. Create a 1D array of numbers from 0 to 9

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# Q. Create a 3×3 numpy array of all True’s

np.ones((3, 3), dtype=bool)
# np.full((3, 3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [11]:
# Q. Extract all odd numbers from arr
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr[np.where(arr % 2)]
# arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

In [12]:
# Q. Replace all odd numbers in arr with -1
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

np.where(arr % 2, -1, arr)
# arr[arr % 2 == 1] = -1

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [15]:
# Q. Convert a 1D array to a 2D array with 2 rows

np.arange(10).reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [68]:
# Q. Print or show only 3 decimal places of the numpy array rand_arr.
rand_arr = np.random.random((5,3))

rand_arr.round(3)
# np.set_printoptions(precision=3)
# rand_arr

array([[0.928, 0.991, 0.307],
       [0.477, 0.176, 0.385],
       [0.324, 0.272, 0.626],
       [0.398, 0.161, 0.402],
       [0.219, 0.858, 0.363]])

In [80]:
# Q. Pretty print rand_arr by suppressing the scientific notation (like 1e10)
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
print(rand_arr)

np.set_printoptions(suppress=True, precision=6)
print(rand_arr)
np.set_printoptions(suppress=False, precision=8) # Reset to default

[[5.434049e-04 2.783694e-04 4.245176e-04]
 [8.447761e-04 4.718856e-06 1.215691e-04]
 [6.707491e-04 8.258528e-04 1.367066e-04]]
[[0.000543 0.000278 0.000425]
 [0.000845 0.000005 0.000122]
 [0.000671 0.000826 0.000137]]


In [81]:
# Q. Limit the number of items printed in python numpy array a to a maximum of 6 elements.
a = np.arange(15)

np.set_printoptions(threshold=6)
print(a)
np.set_printoptions(threshold=1000) # Reset to default

[ 0  1  2 ... 12 13 14]


In [88]:
# Q. Print the full numpy array a without truncating.
a = np.arange(15)

np.set_printoptions(threshold=1000) # Reset to default
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## L2 Difficulty

In [14]:
# Q. Replace all odd numbers in arr with -1 without changing arr
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

np.where(arr % 2, -1, arr), arr

(array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [23]:
# Q. Stack arrays a and b vertically
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.vstack([a, b])
# np.concatenate([a, b], axis=0)
# np.r_[a, b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [26]:
# Q. Stack the arrays a and b horizontally.

np.c_[a, b]
# np.concatenate([a, b], axis=1)
# np.hstack([a, b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [29]:
# Q. Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
a = np.array([1,2,3])
# Desired: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

np.r_[np.repeat(a, 3), np.tile(a, 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [34]:
# Q. Get the common items between a and b
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a, b)

array([2, 4])

In [40]:
# Q. From array a remove all items present in array b
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

np.setdiff1d(a, b)

array([1, 2, 3, 4])

In [41]:
# Q. Get the positions where elements of a and b match
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a == b)

(array([1, 3, 5, 7]),)

In [45]:
# Q. Get all items between 5 and 10 from a.
a = np.array([2, 6, 1, 9, 10, 3, 27])

np.intersect1d(a, np.arange(5, 11))
# a[(a > 4) & (a < 11)]

array([ 6,  9, 10])

In [48]:
# Q. Convert the function maxx that works on two scalars, to work on two arrays.

def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

maxx(1, 5)
#> 5

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max = np.vectorize(maxx, otypes=[float])
pair_max(a, b)

array([6., 7., 9., 8., 9., 7., 5.])

In [51]:
# Q. Swap columns 1 and 2 in the array arr.
arr = np.arange(9).reshape(3,3)

arr[:, [1, 0, 2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [52]:
# Q. Swap rows 1 and 2 in the array arr.
arr = np.arange(9).reshape(3,3)

arr[[1, 0, 2], :]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [53]:
# Q. Reverse the rows of a 2D array arr.
arr = np.arange(9).reshape(3,3)

arr[::-1, :]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [54]:
# Q. Reverse the columns of a 2D array arr.
arr = np.arange(9).reshape(3,3)

arr[:, ::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [61]:
# Q. Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.

np.random.randint(5, 10, size=(5, 3)) + np.random.rand(5, 3)
# rand_arr = np.random.uniform(5,10, size=(5,3))

array([[6.87561319, 9.22219274, 9.8279373 ],
       [5.32141666, 7.53196241, 8.57718079],
       [6.75319933, 6.5813849 , 8.01384743],
       [8.87564907, 7.19498559, 7.22667247],
       [8.0548931 , 6.14746613, 8.73613493]])

In [94]:
# Q. Import the iris dataset keeping the text intact.

np.genfromtxt('data/iris.data', delimiter=',', dtype='object')[:3]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)

In [103]:
# Q. Extract the text column species from the 1D iris imported in previous question.

iris_1d = np.genfromtxt('data/iris.data', delimiter=',', dtype=None)
np.array([i[4] for i in iris_1d[:3]])

/var/folders/t2/x0g2tzrj5_zglz92zl_3jjk00000gn/T/ipykernel_2905/4160492449.py:3: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  iris_1d = np.genfromtxt('data/iris.data', delimiter=',', dtype=None)


array([b'Iris-setosa', b'Iris-setosa', b'Iris-setosa'], dtype='|S11')

In [126]:
# Q. Convert the 1D iris to 2D array iris_2d by omitting the species text field.
iris_1d = np.genfromtxt('data/iris.data', delimiter=',', dtype=None)

np.array([i.tolist()[:-1] for i in iris_1d]).shape

/var/folders/t2/x0g2tzrj5_zglz92zl_3jjk00000gn/T/ipykernel_2905/2173851294.py:2: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  iris_1d = np.genfromtxt('data/iris.data', delimiter=',', dtype=None)


(150, 4)

In [132]:
# Q. Find the mean, median, standard deviation of iris's sepallength (1st column)
iris_1d = np.genfromtxt('data/iris.data', delimiter=',', dtype=None)

col1 = np.array([i[0] for i in iris_1d])

col1.mean(), np.median(col1), col1.std()

/var/folders/t2/x0g2tzrj5_zglz92zl_3jjk00000gn/T/ipykernel_2905/3165742506.py:2: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  iris_1d = np.genfromtxt('data/iris.data', delimiter=',', dtype=None)


(5.843333333333334, 5.8, 0.8253012917851409)

In [136]:
# Q. Create a normalized form of iris's sepallength whose values range exactly between 0 and 1 so that the minimum has value 0 and maximum has value 1.

sepallength = np.genfromtxt('data/iris.data', delimiter=',', dtype='float', usecols=[0])

(sepallength - sepallength.min()) / sepallength.ptp()

array([0.22222222, 0.16666667, 0.11111111, 0.08333333, 0.19444444,
       0.30555556, 0.08333333, 0.19444444, 0.02777778, 0.16666667,
       0.30555556, 0.13888889, 0.13888889, 0.        , 0.41666667,
       0.38888889, 0.30555556, 0.22222222, 0.38888889, 0.22222222,
       0.30555556, 0.22222222, 0.08333333, 0.22222222, 0.13888889,
       0.19444444, 0.19444444, 0.25      , 0.25      , 0.11111111,
       0.13888889, 0.30555556, 0.25      , 0.33333333, 0.16666667,
       0.19444444, 0.33333333, 0.16666667, 0.02777778, 0.22222222,
       0.19444444, 0.05555556, 0.02777778, 0.19444444, 0.22222222,
       0.13888889, 0.22222222, 0.08333333, 0.27777778, 0.19444444,
       0.75      , 0.58333333, 0.72222222, 0.33333333, 0.61111111,
       0.38888889, 0.55555556, 0.16666667, 0.63888889, 0.25      ,
       0.19444444, 0.44444444, 0.47222222, 0.5       , 0.36111111,
       0.66666667, 0.36111111, 0.41666667, 0.52777778, 0.36111111,
       0.44444444, 0.5       , 0.55555556, 0.5       , 0.58333

In [142]:
# Q. Compute the softmax score of sepallength.

sepallength = np.genfromtxt('data/iris.data', delimiter=',', dtype='float', usecols=[0])

(np.exp(sepallength) / np.exp(sepallength).sum()).round(3)

array([0.002, 0.002, 0.001, 0.001, 0.002, 0.003, 0.001, 0.002, 0.001,
       0.002, 0.003, 0.002, 0.002, 0.001, 0.004, 0.004, 0.003, 0.002,
       0.004, 0.002, 0.003, 0.002, 0.001, 0.002, 0.002, 0.002, 0.002,
       0.002, 0.002, 0.001, 0.002, 0.003, 0.002, 0.003, 0.002, 0.002,
       0.003, 0.002, 0.001, 0.002, 0.002, 0.001, 0.001, 0.002, 0.002,
       0.002, 0.002, 0.001, 0.003, 0.002, 0.015, 0.008, 0.013, 0.003,
       0.009, 0.004, 0.007, 0.002, 0.01 , 0.002, 0.002, 0.005, 0.005,
       0.006, 0.004, 0.011, 0.004, 0.004, 0.007, 0.004, 0.005, 0.006,
       0.007, 0.006, 0.008, 0.01 , 0.012, 0.011, 0.005, 0.004, 0.003,
       0.003, 0.004, 0.005, 0.003, 0.005, 0.011, 0.007, 0.004, 0.003,
       0.003, 0.006, 0.004, 0.002, 0.004, 0.004, 0.004, 0.007, 0.002,
       0.004, 0.007, 0.004, 0.016, 0.007, 0.009, 0.027, 0.002, 0.02 ,
       0.011, 0.018, 0.009, 0.008, 0.012, 0.004, 0.004, 0.008, 0.009,
       0.03 , 0.03 , 0.005, 0.013, 0.004, 0.03 , 0.007, 0.011, 0.018,
       0.007, 0.006,